### ISSUE TITLE
Is there a way to get ioredis instance from nestjs-redis?

### ISSUE THREAD

**Issue by alexandreaugusto** [skunight/nestjs-redis#49]
I'm using this Nestjs Redis component and I saw that component is using ioredis. What happens is that I want to save geoinformation through GEOADD command available on Redis and available also in the ioredis.

So, how can I get an ioredis instance from a Nestjs-Redis instance? Is it possible?

Thanks in advance!

**Comment by skunight** [comment]
RedisService.getClient() is return a ioredis instance

**Comment by alexandreaugusto** [comment]
And why when I execute this code:

```
const client = await this.redisService.getClient('redis');
client.geoadd("user:"+location.user.id+":cell:"+location.cell, location.longitude, location.latitude, <string><any>location.id)
```

I've got this error?

src/location/location.service.ts:101:12 - error TS2339: Property 'geoadd' does not exist on type 'Redis'.

101     client.geoadd("user:"+location.user.id+":cell:"+location.cell, location.longitude, location.latitude, <string><any>location.id)

If I create a separated connection using specifically ioredis instance, works perfectly...

```
const Redis = require('ioredis')
const redis = new Redis({        
    name: 'vai-chover',
    host: redisConfigService.get("REDIS_HOST"),
    port: Number(redisConfigService.get("REDIS_PORT")),
    password: redisConfigService.get("REDIS_PASSWORD"),
    db: Number(redisConfigService.get("REDIS_DB")),
    keyPrefix: redisConfigService.get("REDIS_PREFIX"),
})

redis.geoadd("user:"+location.user.id+":cell:"+location.cell, location.longitude, location.latitude, <string><any>location.id)
```

but I want to use the same connection and not another one.

**Comment by skunight** [comment]
> I'm using this Nestjs Redis component and I saw that component is using ioredis. What happens is that I want to save geoinformation through GEOADD command available on Redis and available also in the ioredis.
> 
> So, how can I get an ioredis instance from a Nestjs-Redis instance? Is it possible?
> 
> Thanks in advance!

/**
 * Send a command to Redis
 *
 * This method is used internally by the `Redis#set`, `Redis#lpush` etc.
 * Most of the time you won't invoke this method directly.
 * However when you want to send a command that is not supported by ioredis yet,
 * this command will be useful.
 *
 * @method sendCommand
 * @memberOf Redis#
 * @param {Command} command - The Command instance to send.
 * @see {@link Command}
 * @example
 * ```js
 * var redis = new Redis();
 *
 * // Use callback
 * var get = new Command('get', ['foo'], 'utf8', function (err, result) {
 *   console.log(result);
 * });
 * redis.sendCommand(get);
 *
 * // Use promise
 * var set = new Command('set', ['foo', 'bar'], 'utf8');
 * set.promise.then(function (result) {
 *   console.log(result);
 * });
 * redis.sendCommand(set);
 * ```
 * @private
 */
