### ISSUE TITLE
Publish the last changes to npm

### ISSUE THREAD

**Issue by kolegm** [skunight/nestjs-redis#98]
Hi, @skunight 
Could you please publish the last version of your package into the public NPM registry?

Would be great to use the last adaptation for nestjs@8.*

Thank you in advance

**Comment by loweoj** [comment]
Just use https://github.com/liaoliaots/nestjs-redis... Seems better maintained :+1:

**Comment by kolegm** [comment]
we decided not to use 'nestjs-redis' at all.
Cheers
